export enum tagTypes {
	student = 'student',
	faculty = 'faculty',
	admin = 'admin',
	user = 'user',
	permission = 'permission',
	academicFaculty = 'academic-faculty',
	academicDepartment = 'academic-department',
	academicSemester = 'academic-semester',
	department = 'department',
	building = 'building',
	room = 'room',
	course = 'course',
	semesterRegistration = 'semester-registration',
	offeredCourse = 'offered-course',
	offeredCourseSection = 'offered-course-section',
	offeredCourseSchedule = 'offered-course-schedule',
	courseRegisration = 'course-registration',
	studentEnrolledCourse = 'student-enrolled-course',
	payment = 'payment',
}
export const tagTypelist = [
	tagTypes.student,
	tagTypes.faculty,
	tagTypes.admin,
	tagTypes.user,
	tagTypes.permission,
	tagTypes.academicFaculty,
	tagTypes.academicDepartment,
	tagTypes.academicSemester,
	tagTypes.department,
	tagTypes.building,
	tagTypes.room,
	tagTypes.course,
	tagTypes.semesterRegistration,
	tagTypes.offeredCourse,
	tagTypes.offeredCourseSection,
	tagTypes.offeredCourseSchedule,
	tagTypes.courseRegisration,
	tagTypes.studentEnrolledCourse,
	tagTypes.payment,
];
